"https://{default}/":
  type: upstream
  upstream: "civictrak"
  cache:
    enabled: true
    default_ttl: 300
  redirects:
    paths:
      "^http://":
        to: "https://{default}/"
        status: 301
